import { createSlice } from '@reduxjs/toolkit';

/**
 * createSlice is a function that accepts an initial state, an object of reducer functions, 
 * and a "slice name", and automatically generates action creators and action types that correspond to the reducers and state.
 * This simplifies the Redux boilerplate significantly.
 */
const todoSlice = createSlice({
  name: 'todos', // The name of the slice, used as a prefix for generated action types
  initialState: {
    todos: [], // The initial state is an object with a 'todos' array
  },
  reducers: {
    /**
     * Reducer to add a new todo.
     * @param {object} state - The current state of this slice.
     * @param {object} action - The action dispatched.
     * action.payload contains the text for the new todo.
     */
    addTodo: (state, action) => {
      state.todos.push({
        id: Date.now(), // Generate a unique ID based on the current timestamp
        text: action.payload, // The text passed when dispatching the action
        completed: false, // By default, a new todo is not completed
      });
    },
    /**
     * Reducer to toggle the completed status of a todo.
     * @param {object} state - The current state.
     * @param {object} action - The action dispatched.
     * action.payload contains the ID of the todo to toggle.
     */
    toggleTodo: (state, action) => {
      const todo = state.todos.find((t) => t.id === action.payload);
      if (todo) {
        todo.completed = !todo.completed; // Toggle the boolean value
      }
    },
    /**
     * Reducer to delete a todo.
     * @param {object} state - The current state.
     * @param {object} action - The action dispatched.
     * action.payload contains the ID of the todo to delete.
     */
    deleteTodo: (state, action) => {
      // Filter out the todo that matches the ID in the payload
      state.todos = state.todos.filter((t) => t.id !== action.payload);
    },
    /**
     * Reducer to clear all todos.
     * @param {object} state - The current state.
     */
    clearTodos: (state) => {
      state.todos = []; // Reset the todos array to an empty array
    },
  },
});

// Export the action creators generated by createSlice so they can be dispatched from components
export const { addTodo, toggleTodo, deleteTodo, clearTodos } = todoSlice.actions;

// Export the reducer function generated by createSlice to be used in the store configuration
export default todoSlice.reducer;
